# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('open', models.BooleanField(default=True)),
            ],
        ),
    ]
